require 'rspec'

require_relative '../lib/patron'
require_relative '../lib/contexto_de_ejecucion'
require_relative '../lib/proc_matcher'
require_relative '../lib/evaluator'
require_relative '../lib/clases'
require_relative '../lib/duck_matcher'
require_relative '../lib/list_matcher'
require_relative '../lib/type_matcher'
require_relative '../lib/val_matcher'